import { readFileSync } from "node:fs";
import path from "node:path";
import { compile } from "tailwindcss";
import { describe, expect, it } from "vitest";
import { expectedOutputs, scopePreflight, scopeSelector, ISLAND_ROOT } from "../gallery/preflight-scope.mjs";
import { ROOT, readSource } from "./source-files";

// styles/preflight-scoped.css (1.3.0, PrefabOps restyle plan G19 / M1, library spec §13.2):
// Tailwind's preflight applied only inside `.ops-ui-root`, generated rule for rule from the
// pinned tailwindcss by gallery/preflight-scope.mjs. The gallery's own reset
// (gallery/app/preflight-global.css) is generated by the same transform.

const PREFLIGHT = readFileSync(path.join(ROOT, "node_modules/tailwindcss/preflight.css"), "utf8");

describe("the generated files", () => {
  it("are what the generator writes from the pinned tailwindcss (run node gallery/preflight-scope.mjs)", () => {
    for (const { file, text } of expectedOutputs() as { file: string; text: string }[]) {
      expect(readSource(file), file).toBe(text);
    }
  });

  it("styles/preflight-scoped.css ships (styles/*.css) and has no @theme and no double quote in a comment", () => {
    const scoped = readSource("styles/preflight-scoped.css");
    expect(scoped).not.toMatch(/@theme\b/);
    for (const comment of scoped.match(/\/\*[\s\S]*?\*\//g) ?? []) expect(comment).not.toContain('"');
  });
});

describe("scopeSelector", () => {
  const R = ISLAND_ROOT as string;
  const cases: [string, string][] = [
    ["*", ":where(.ops-ui-root, .ops-ui-root *)"],
    ["::after", ":where(.ops-ui-root, .ops-ui-root *)::after"],
    ["html", ":where(.ops-ui-root)"],
    [":host", ":where(.ops-ui-root)"],
    ["h1", "h1:where(.ops-ui-root, .ops-ui-root *)"],
    ["abbr:where([title])", "abbr:where([title]):where(.ops-ui-root, .ops-ui-root *)"],
    [
      ":where(select:is([multiple], [size])) optgroup option",
      ":where(select:is([multiple], [size])) optgroup option:where(.ops-ui-root, .ops-ui-root *)",
    ],
    [
      "input:where([type='button'], [type='reset'], [type='submit'])",
      "input:where([type='button'], [type='reset'], [type='submit']):where(.ops-ui-root, .ops-ui-root *)",
    ],
    ["::-webkit-search-decoration", ":where(.ops-ui-root, .ops-ui-root *)::-webkit-search-decoration"],
    ["[hidden]:where(:not([hidden='until-found']))", "[hidden]:where(:not([hidden='until-found'])):where(.ops-ui-root, .ops-ui-root *)"],
  ];
  it.each(cases)("%s", (selector, scoped) => expect(scopeSelector(selector, R)).toBe(scoped));
});

/** Every `selector { declarations }` of a compiled stylesheet, at-rules flattened, keyed by declarations. */
function rules(css: string): { selector: string; body: string }[] {
  const out: { selector: string; body: string }[] = [];
  const text = css.replace(/\/\*[\s\S]*?\*\//g, "");
  for (const m of text.matchAll(/([^{}@;]+)\{([^{}]*)\}/g)) {
    if (text[m.index - 1] === "@") continue; // an empty at-rule block, not a style rule
    out.push({ selector: m[1].trim(), body: m[2].replace(/\s+/g, " ").trim() });
  }
  // The @theme block the test adds compiles to the one :root rule; it is not preflight's.
  return out.filter((rule) => rule.selector !== ":root, :host");
}

describe("compiled, rule for rule", () => {
  it("every preflight rule has its scoped twin with the same declarations, and nothing applies outside .ops-ui-root", async () => {
    const build = async (source: string) => (await compile(`@theme { --default-font-family: x; }\n${source}`)).build([]);
    const plain = rules(await build(PREFLIGHT));
    const scoped = rules(await build(scopePreflight(PREFLIGHT, ISLAND_ROOT, "/* header */")));
    expect(plain.length).toBeGreaterThan(30);
    expect(scoped.map((r) => r.body)).toEqual(plain.map((r) => r.body));
    for (const rule of scoped) {
      expect(rule.selector, rule.selector).not.toBe("");
      // Each selector of the list carries the scope (the root itself, or root + descendants).
      for (const selector of rule.selector.split(/,\s*(?![^()]*\))/)) {
        expect(selector, rule.selector).toMatch(/:where\(\.ops-ui-root(, \.ops-ui-root \*)?\)/);
      }
    }
  });
});
