import { describe, expect, it } from "vitest";
import { fixtureFromBrandCss } from "../tools/pull-brands.mjs";
import { checkBrandCss, parseTokenContract } from "../sync/sync-ops-ui.mjs";
import { readSource } from "./source-files";

// tools/pull-brands.mjs (spec §11.2): an app's brand.css becomes the gallery fixture by
// rewriting :root to html[data-brand=x] and nothing else.
describe("pull-brands", () => {
  const contract = parseTokenContract(readSource("styles/tokens.css"));
  const appBrand = readSource("gallery/brands/finaops.css").replace(/^html\[data-brand=finaops\] \{/m, ":root {");

  it("rewrites the one :root rule and keeps every declaration", () => {
    const fixture = fixtureFromBrandCss(appBrand, "finaops", "fina-ops@abc1234");
    expect(fixture.split("\n")[0]).toContain("GENERATED by tools/pull-brands.mjs from fina-ops@abc1234");
    expect(fixture).toContain("html[data-brand=finaops] {");
    expect(fixture).not.toMatch(/^:root/m);
    expect(fixture.split("\n").slice(1).join("\n")).toBe(appBrand.replace(":root {", "html[data-brand=finaops] {"));
    expect(checkBrandCss(fixture, contract, { selector: "html[data-brand=finaops]" })).toEqual([]);
  });

  it("refuses a brand.css that is not one :root rule", () => {
    expect(() => fixtureFromBrandCss(`${appBrand}\n:root { --brand-accent: red; }\n`, "finaops", "x")).toThrow(/exactly one :root/);
    expect(() => fixtureFromBrandCss("html { }", "finaops", "x")).toThrow(/found 0/);
  });
});
