import { execFile, execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { afterAll, describe, expect, it } from "vitest";
import { resolveRelease } from "../sync/sync-ops-ui.mjs";
import {
  bumpLevel,
  changelogSection,
  classifySurface,
  classifyTokens,
  componentNames,
  interactionLines,
  isPureRebaseline,
  isReviewed,
  surfaceStatements,
} from "../tools/release.mjs";
import { ROOT, readSource } from "./source-files";

// The release script end to end (spec §4.2, §12.1 L7a): the REAL tools/release.mjs, run with node
// against temporary git repositories - a fake library with a bare "origin" to fetch from and push
// to, and package scripts standing in for the four gates (each appends its name to a log outside
// the tree, and FAIL_GATE=<name> makes that one fail).

const RELEASE = path.join(ROOT, "tools/release.mjs");
const SANDBOX = mkdtempSync(path.join(os.tmpdir(), "ops-ui-release-test-"));
afterAll(() => rmSync(SANDBOX, { recursive: true, force: true }));
const T = { timeout: 120_000 };
const run = promisify(execFile);

const PKG = JSON.parse(readSource("package.json"));
const IDENTITY = {
  GIT_AUTHOR_NAME: "Test",
  GIT_AUTHOR_EMAIL: "test@example.invalid",
  GIT_COMMITTER_NAME: "Test",
  GIT_COMMITTER_EMAIL: "test@example.invalid",
};

let counter = 0;
function dir(name: string) {
  const d = path.join(SANDBOX, `${name}-${++counter}`);
  mkdirSync(d, { recursive: true });
  return d;
}

function git(repo: string, ...args: string[]) {
  return execFileSync("git", ["-c", "commit.gpgsign=false", "-C", repo, ...args], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    env: { ...process.env, ...IDENTITY },
  }).trim();
}

function write(root: string, rel: string, content: string | Buffer) {
  const file = path.join(root, rel);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, content);
}

function read(root: string, rel: string) {
  return readFileSync(path.join(root, rel), "utf8");
}

const SURFACE = [
  "// @latro/ops-ui declaration surface - GENERATED by tools/api-surface.mjs (tsc --emitDeclarationOnly over src/).",
  "",
  "// src/components/badge.d.ts",
  'import type { BadgeVariant } from "../types";',
  "export type { BadgeVariant };",
  "export declare function Badge({ tone }: {",
  "    tone: BadgeVariant;",
  '}): import("react").JSX.Element;',
  "",
  "// src/components/button.d.ts",
  "export declare function Button({ size }: {",
  '    size?: "sm" | "md";',
  '}): import("react").JSX.Element;',
  "export type ButtonTone = \"a\" | \"b\";",
  "",
].join("\n");

const BUTTON = `"use client";\n\nexport function Button() {\n  return <button className="rounded bg-primary text-white">x</button>;\n}\n`;
const GATE = `const [name] = process.argv.slice(2);\nrequire("node:fs").appendFileSync(process.env.GATE_LOG, name + "\\n");\nif (process.env.FAIL_GATE === name) process.exit(3);\n`;

const FIRST_CHANGELOG =
  "# Changelog\n\n## 1.0.0 — 2026-09-30\nAdded: the kit.\nVisible: none (a pure extraction).\nUpgrade steps: none (the first release).\n";

type Repo = { lib: string; origin: string; gateLog: string };

/** A library at 0.0.0 with its origin, everything pushed. */
function library(changelog = FIRST_CHANGELOG): Repo {
  const origin = dir("origin");
  git(origin, "init", "-q", "--bare", "-b", "main");
  const lib = dir("lib");
  git(lib, "init", "-q", "-b", "main");
  git(lib, "remote", "add", "origin", origin);
  const scripts = Object.fromEntries(["typecheck", "lint", "test", "shots"].map((g) => [g, `node gate.cjs ${g}`]));
  write(lib, "package.json", `${JSON.stringify({ name: "@latro/ops-ui", version: "0.0.0", private: true, scripts, peerDependencies: PKG.peerDependencies }, null, 2)}\n`);
  write(lib, "gate.cjs", GATE);
  write(lib, "src/version.ts", '/** The released version. */\nexport const OPS_UI_VERSION = "0.0.0";\n');
  write(lib, "src/components/button.tsx", BUTTON);
  write(lib, "styles/tokens.css", readSource("styles/tokens.css"));
  write(lib, "api-surface.d.txt", SURFACE);
  write(lib, "CHANGELOG.md", changelog);
  write(lib, "gallery/__screenshots__/1440/workforce/button--matrix.png", "png-1");
  write(lib, "gallery/__screenshots__/375/workforce/button--matrix.png", "png-2");
  write(lib, "gallery/playwright.config.ts", "// pinned\n");
  commit(lib, "L1: scaffold");
  return { lib, origin, gateLog: path.join(dir("log"), "gates.log") };
}

function commit(lib: string, subject: string, pushIt = true) {
  git(lib, "add", "-A");
  git(lib, "commit", "-q", "-m", subject);
  if (pushIt) git(lib, "push", "-q", "origin", "main");
}

async function release(repo: Repo, args: string[], env: Record<string, string> = {}) {
  try {
    const { stdout, stderr } = await run(process.execPath, [RELEASE, ...args], {
      cwd: repo.lib,
      env: { ...process.env, ...IDENTITY, GATE_LOG: repo.gateLog, ...env },
      encoding: "utf8",
    });
    return { status: 0, stdout, stderr };
  } catch (error) {
    const e = error as { code?: number; stdout?: string; stderr?: string };
    return { status: e.code ?? -1, stdout: e.stdout ?? "", stderr: e.stderr ?? "" };
  }
}

function gatesRun(repo: Repo) {
  try {
    return readFileSync(repo.gateLog, "utf8").trim().split("\n").filter(Boolean);
  } catch {
    return [];
  }
}

/** A library released at 1.0.0 (by the script itself), with a new CHANGELOG section to write. */
async function released(): Promise<Repo> {
  const repo = library();
  const result = await release(repo, ["1.0.0"]);
  if (result.status !== 0) throw new Error(`the 1.0.0 release of the fixture failed: ${result.stderr}`);
  rmSync(repo.gateLog, { force: true });
  return repo;
}

function addSection(repo: Repo, section: string) {
  const current = read(repo.lib, "CHANGELOG.md");
  write(repo.lib, "CHANGELOG.md", current.replace("# Changelog\n\n", `# Changelog\n\n${section}\n`));
}

const MAJOR_LINES = "Visible: button--matrix at 1440 (the fill).\nUpgrade steps: node scripts/sync-ops-ui.mjs --version 2.0.0\n";

describe("release rules (pure)", () => {
  it("accepts only the next patch, minor or major", () => {
    expect(bumpLevel("0.0.0", "1.0.0")).toBe("major");
    expect(bumpLevel("0.0.0", "0.1.0")).toBe("minor");
    expect(bumpLevel("0.0.0", "0.0.1")).toBe("patch");
    expect(bumpLevel("1.2.3", "1.2.4")).toBe("patch");
    expect(bumpLevel("1.2.3", "1.3.0")).toBe("minor");
    expect(bumpLevel("1.2.3", "2.0.0")).toBe("major");
    for (const wrong of ["1.2.5", "1.4.0", "3.0.0", "1.3.1", "2.0.1", "1.2.3", "1.2.2", "1.2", "v1.2.4", "1.2.4-rc.1"]) {
      expect(bumpLevel("1.2.3", wrong), wrong).toBeNull();
    }
  });

  it("reads a dated CHANGELOG section and its labelled lines", () => {
    const log = "# Changelog\n\n## 1.1.0 — 2026-10-06\nAdded: x.\nReviewed: RowMenu - same.\n\n## 1.0.0 — unreleased\nAdded: y.\n";
    expect(changelogSection(log, "1.1.0")).toEqual({ heading: "## 1.1.0 — 2026-10-06", date: "2026-10-06", lines: ["Added: x.", "Reviewed: RowMenu - same."] });
    expect(changelogSection(log, "1.0.0")?.date).toBeNull();
    expect(changelogSection("## 1.0.0 — 2026-02-30\n", "1.0.0")?.date).toBeNull();
    expect(changelogSection(log, "1.0")).toBeNull();
    expect(changelogSection(log, "2.0.0")).toBeNull();
  });

  it("names a file's component the way a Reviewed: line may", () => {
    expect(componentNames("src/components/row-menu.tsx")).toEqual(["row-menu", "RowMenu"]);
    expect(componentNames("src/stories/button.stories.tsx")).toEqual(["button", "Button"]);
    expect(isReviewed(["RowMenu - the same output on hover and focus"], "src/components/row-menu.tsx")).toBe(true);
    expect(isReviewed(["row-menu: unchanged"], "src/components/row-menu.tsx")).toBe(true);
    // A word, not a substring: ExternalButtonLink does not name button.tsx.
    expect(isReviewed(["ExternalButtonLink is new"], "src/components/button.tsx")).toBe(false);
  });

  it("finds interaction-only styles and matchMedia in changed lines only", () => {
    const diff = [
      "diff --git a/src/components/button.tsx b/src/components/button.tsx",
      "--- a/src/components/button.tsx",
      "+++ b/src/components/button.tsx",
      '-  "bg-primary hover:bg-primary-hover",',
      '+  "bg-primary hover:bg-primary",',
      '   "focus-visible:ring-2",',
      "diff --git a/src/components/segmented.tsx b/src/components/segmented.tsx",
      '+  "sm:pointer-coarse:py-2"',
      '+  "text-sm"',
      "diff --git a/src/lib/use-dismissable.ts b/src/lib/use-dismissable.ts",
      "+  const touch = window.matchMedia(\"(pointer: coarse)\");",
      '+  "data-[state=open]:bg-x aria-selected:bg-y"',
    ].join("\n");
    expect(interactionLines(diff).map((l) => l.file)).toEqual([
      "src/components/button.tsx",
      "src/components/button.tsx",
      "src/components/segmented.tsx",
      "src/lib/use-dismissable.ts",
    ]);
  });

  it("maps a removed surface line to the declaration around it", () => {
    const statements = surfaceStatements(SURFACE);
    expect(statements.map((s) => [s.file, s.names])).toEqual([
      ["src/components/badge.d.ts", ["BadgeVariant"]],
      ["src/components/badge.d.ts", ["BadgeVariant"]],
      ["src/components/badge.d.ts", ["Badge"]],
      ["src/components/button.d.ts", ["Button"]],
      ["src/components/button.d.ts", ["ButtonTone"]],
    ]);
    // The size union's line (12) belongs to Button.
    const diff = "@@ -12 +12 @@\n-    size?: \"sm\" | \"md\";\n+    size?: \"sm\" | \"md\" | \"lg\";\n@@ -14,0 +15 @@\n+export type ButtonSize = \"sm\";\n";
    expect(classifySurface(SURFACE, diff)).toEqual({
      changed: [{ name: "Button", file: "src/components/button.d.ts", line: 12 }],
      unnamed: [],
      added: 2,
    });
    expect(classifySurface(SURFACE, "@@ -14,0 +15 @@\n+export type ButtonSize = \"sm\";\n")).toEqual({ changed: [], unnamed: [], added: 1 });
    // tsc's module marker is not API either way.
    expect(classifySurface(`${SURFACE}export {};\n`, "@@ -16 +15,0 @@\n-export {};\n")).toEqual({ changed: [], unnamed: [], added: 0 });
  });

  it("reads the real api-surface.d.txt into named statements", () => {
    const statements = surfaceStatements(readSource("api-surface.d.txt"));
    expect(statements.length).toBeGreaterThan(100);
    expect(statements.every((s) => s.file.startsWith("src/"))).toBe(true);
    // Every statement names what it declares, except tsc's `export {};` module marker.
    const text = readSource("api-surface.d.txt").split("\n");
    expect(statements.filter((s) => s.names.length === 0 && text[s.start - 1] !== "export {};")).toEqual([]);
    expect(statements.some((s) => s.names.includes("Button") && s.file === "src/components/button.d.ts")).toBe(true);
  });

  it("classifies token contract changes", () => {
    const tokens = readSource("styles/tokens.css");
    expect(classifyTokens(tokens, tokens)).toEqual({ newRequired: [], removed: [], changed: [], added: [] });
    const required = tokens.replace("--color-accent: var(--brand-accent);", "--color-accent: var(--brand-accent);\n  --color-rail: var(--brand-rail);");
    expect(classifyTokens(tokens, required)).toEqual({ newRequired: ["--brand-rail"], removed: [], changed: [], added: ["--color-rail"] });
    const fixed = tokens.replace("--radius-control: 6px;", "--radius-control: 7px;\n  --radius-pill: 999px;");
    expect(classifyTokens(tokens, fixed)).toEqual({ newRequired: [], removed: [], changed: ["--radius-control"], added: ["--radius-pill"] });
    expect(classifyTokens(tokens, tokens.replace("  --text-micro: 11px;\n", "")).removed).toEqual(["--text-micro"]);
  });

  it("knows a pure rebaseline", () => {
    const shots = ["gallery/__screenshots__/1440/workforce/a.png", "gallery/playwright.config.ts", "gallery/fonts/glyphs.css"];
    expect(isPureRebaseline("shots: rebaseline (Chromium 1200)", shots)).toBe(true);
    expect(isPureRebaseline("shots: rebaseline (Chromium 1200)", [...shots, "src/components/button.tsx"])).toBe(false);
    expect(isPureRebaseline("shots: rebaseline (x)", ["styles/tokens.css"])).toBe(false);
    expect(isPureRebaseline("shots: rebaseline", shots)).toBe(false);
    expect(isPureRebaseline("Rebaseline the shots", shots)).toBe(false);
  });
});

// Concurrent: every test has its own repositories, and the gates run in child processes.
describe.concurrent("pnpm release (tools/release.mjs against temporary repositories)", () => {
  it("releases 1.0.0: the gates, one commit of exactly two files, main and release/v1.0.0 pushed, the sync finds it", T, async ({ expect }) => {
    const repo = library();
    const before = git(repo.lib, "rev-parse", "HEAD");
    const result = await release(repo, ["1.0.0", "--trailer", "Co-Authored-By: Someone <someone@example.invalid>"]);
    expect(result.status, result.stderr).toBe(0);
    expect(gatesRun(repo)).toEqual(["typecheck", "lint", "test", "shots"]);
    const head = git(repo.lib, "rev-parse", "HEAD");
    expect(git(repo.lib, "rev-parse", "HEAD~1")).toBe(before);
    expect(git(repo.lib, "log", "-1", "--format=%s", "HEAD")).toBe("release: v1.0.0");
    expect(git(repo.lib, "log", "-1", "--format=%b", "HEAD")).toContain("Co-Authored-By: Someone <someone@example.invalid>");
    expect(git(repo.lib, "show", "--name-only", "--format=", "HEAD").split("\n").sort()).toEqual(["package.json", "src/version.ts"]);
    expect(JSON.parse(read(repo.lib, "package.json")).version).toBe("1.0.0");
    expect(read(repo.lib, "src/version.ts")).toBe('/** The released version. */\nexport const OPS_UI_VERSION = "1.0.0";\n');
    expect(git(repo.origin, "rev-parse", "main")).toBe(head);
    expect(git(repo.origin, "rev-parse", "release/v1.0.0")).toBe(head);
    expect(git(repo.origin, "tag", "--list")).toBe("");
    expect(git(repo.lib, "status", "--porcelain")).toBe("");
    expect(result.stdout).toContain("node scripts/sync-ops-ui.mjs --version 1.0.0");
    // What an app's sync resolves: the one release commit, the branch agreeing.
    git(repo.lib, "fetch", "-q", "origin");
    expect(resolveRelease(repo.lib, "1.0.0")).toBe(head);
  });

  it("step 1: refuses off main, on a dirty tree, on unpushed history and on a version that is not next", T, async ({ expect }) => {
    const repo = library();
    const head = git(repo.lib, "rev-parse", "HEAD");
    for (const version of ["1.0.1", "2.0.0", "0.0.0", "0.2.0"]) {
      const r = await release(repo, [version]);
      expect(r.status, version).toBe(1);
      expect(r.stderr).toContain(`${version} is not the next patch, minor or major after 0.0.0`);
    }
    write(repo.lib, "stray.txt", "x");
    let r = await release(repo, ["1.0.0"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toContain("the working tree is not clean");
    rmSync(path.join(repo.lib, "stray.txt"));
    write(repo.lib, "README.md", "local\n");
    commit(repo.lib, "local only", false);
    r = await release(repo, ["1.0.0"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toMatch(/HEAD \(\w{7}\) is not origin\/main \(\w{7}\): push first/);
    git(repo.lib, "push", "-q", "origin", "main");
    git(repo.lib, "checkout", "-q", "-b", "elsewhere");
    r = await release(repo, ["1.0.0"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toContain("not on main (on elsewhere)");
    git(repo.lib, "checkout", "-q", "main");
    // Nothing ran and nothing was written by any refusal.
    expect(gatesRun(repo)).toEqual([]);
    expect(git(repo.origin, "branch", "--list")).toBe("* main");
    expect(git(repo.lib, "log", "--format=%s", `${head}..HEAD`)).toBe("local only");
    // Usage errors exit 2.
    expect((await release(repo, ["1.0"])).status).toBe(2);
    expect((await release(repo, [])).status).toBe(2);
    expect((await release(repo, ["1.0.0", "--compatible"])).status).toBe(2);
  });

  it("step 1: refuses a failed fetch and an existing release branch", T, async ({ expect }) => {
    const repo = library();
    git(repo.origin, "branch", "release/v1.0.0", "main");
    let r = await release(repo, ["1.0.0"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toContain("origin already has a branch release/v1.0.0");
    git(repo.lib, "remote", "set-url", "origin", path.join(SANDBOX, "no-such-origin"));
    r = await release(repo, ["1.0.0"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toContain("git fetch origin failed");
  });

  it("step 5: refuses an undated section, a missing section and a major without Visible: / Upgrade steps:", T, async ({ expect }) => {
    let repo = library("# Changelog\n\n## 1.0.0 — unreleased\nAdded: the kit.\nVisible: none.\nUpgrade steps: none.\n");
    let r = await release(repo, ["1.0.0"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toContain('date the section: "## 1.0.0 — unreleased" must read "## 1.0.0 — YYYY-MM-DD"');
    repo = library("# Changelog\n");
    r = await release(repo, ["1.0.0"]);
    expect(r.stderr).toContain('CHANGELOG.md has no "## 1.0.0 — YYYY-MM-DD" section');
    repo = library("# Changelog\n\n## 1.0.0 — 2026-09-30\nAdded: the kit.\n");
    r = await release(repo, ["1.0.0"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toContain('a major needs "Visible:"');
    expect(r.stderr).toContain('a major needs "Upgrade steps:"');
    expect(gatesRun(repo)).toEqual([]);
  });

  it("step 2: a failing gate refuses and commits nothing", T, async ({ expect }) => {
    const repo = library();
    const head = git(repo.lib, "rev-parse", "HEAD");
    const r = await release(repo, ["1.0.0"], { FAIL_GATE: "test" });
    expect(r.status).toBe(1);
    expect(r.stderr).toContain("gate pnpm test failed");
    expect(gatesRun(repo)).toEqual(["typecheck", "lint", "test"]);
    expect(git(repo.lib, "rev-parse", "HEAD")).toBe(head);
    expect(git(repo.lib, "status", "--porcelain")).toBe("");
    expect(git(repo.origin, "branch", "--list")).toBe("* main");
  });

  it("--dry-run runs the checks and the gates and writes nothing", T, async ({ expect }) => {
    const repo = library();
    const head = git(repo.lib, "rev-parse", "HEAD");
    const r = await release(repo, ["1.0.0", "--dry-run"]);
    expect(r.status, r.stderr).toBe(0);
    expect(r.stdout).toContain('dry run: would write package.json and src/version.ts (0.0.0 → 1.0.0), commit "release: v1.0.0"');
    expect(gatesRun(repo)).toEqual(["typecheck", "lint", "test", "shots"]);
    expect(git(repo.lib, "rev-parse", "HEAD")).toBe(head);
    expect(git(repo.lib, "status", "--porcelain")).toBe("");
    expect(git(repo.origin, "branch", "--list")).toBe("* main");
  });

  it("step 7: a refused branch push is a warning; main is pushed and no tag is made", T, async ({ expect }) => {
    const repo = library();
    write(repo.origin, "hooks/pre-receive", '#!/bin/sh\nwhile read old new ref; do\n  case "$ref" in refs/heads/release/*) echo "refs refused" >&2; exit 1;; esac\ndone\nexit 0\n');
    execFileSync("chmod", ["+x", path.join(repo.origin, "hooks/pre-receive")]);
    const r = await release(repo, ["1.0.0"]);
    expect(r.status, r.stderr).toBe(0);
    expect(r.stdout).toContain('warning: the push of release/v1.0.0 was refused; the commit marker "release: v1.0.0" is enough for the sync');
    expect(git(repo.origin, "log", "-1", "--format=%s", "main")).toBe("release: v1.0.0");
    expect(git(repo.origin, "branch", "--list", "release/*")).toBe("");
    expect(git(repo.lib, "rev-parse", "release/v1.0.0")).toBe(git(repo.lib, "rev-parse", "HEAD"));
  });

  it("step 4: a docs-only change is a patch", T, async ({ expect }) => {
    const repo = await released();
    write(repo.lib, "README.md", "docs\n");
    addSection(repo, "## 1.0.1 — 2026-10-01\nFixed: the README.\n");
    commit(repo.lib, "docs");
    const r = await release(repo, ["1.0.1"]);
    expect(r.status, r.stderr).toBe(0);
    expect(r.stdout).toContain("release 1.0.1: patch; required since v1.0.0");
    expect(git(repo.lib, "log", "-1", "--format=%s")).toBe("release: v1.0.1");
  });

  it("step 4: an added declaration needs a minor", T, async ({ expect }) => {
    const repo = await released();
    write(repo.lib, "api-surface.d.txt", `${SURFACE}// src/components/tag.d.ts\nexport declare function Tag(): null;\n`);
    addSection(repo, "## 1.0.1 — 2026-10-01\nAdded: Tag.\n");
    commit(repo.lib, "Tag");
    let r = await release(repo, ["1.0.1"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toContain("1.0.1 is a patch, but the changes since v1.0.0");
    expect(r.stderr).toContain("require a minor");
    expect(r.stderr).toContain("api-surface.d.txt: 1 added line(s)");
    write(repo.lib, "CHANGELOG.md", read(repo.lib, "CHANGELOG.md").replace("## 1.0.1 — 2026-10-01", "## 1.1.0 — 2026-10-01"));
    commit(repo.lib, "changelog");
    r = await release(repo, ["1.1.0"]);
    expect(r.status, r.stderr).toBe(0);
  });

  it("step 4: a changed declaration is a major unless --compatible names it with a Compatible: line", T, async ({ expect }) => {
    const repo = await released();
    write(repo.lib, "api-surface.d.txt", SURFACE.replace('size?: "sm" | "md";', 'size?: "sm" | "md" | "lg";'));
    addSection(repo, "## 1.1.0 — 2026-10-01\nChanged: Button takes size lg.\n");
    commit(repo.lib, "Button lg");
    let r = await release(repo, ["1.1.0"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toContain("require a major");
    expect(r.stderr).toContain("api-surface.d.txt: src/components/button.d.ts Button is removed or changed");
    r = await release(repo, ["1.1.0", "--compatible", "Button"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toContain('--compatible Button needs the line "Compatible: Button - <why an unchanged call site renders the same>"');
    r = await release(repo, ["1.1.0", "--compatible", "Badge"]);
    expect(r.stderr).toContain("--compatible Badge: no removed or changed declaration of api-surface.d.txt is named Badge");
    write(repo.lib, "CHANGELOG.md", read(repo.lib, "CHANGELOG.md").replace("Changed: Button takes size lg.\n", "Changed: Button takes size lg.\nCompatible: Button - the size union only widens; every existing call type-checks and renders the same.\n"));
    commit(repo.lib, "changelog");
    r = await release(repo, ["1.1.0", "--compatible", "Button"]);
    expect(r.status, r.stderr).toBe(0);
    expect(git(repo.lib, "log", "-1", "--format=%b")).toContain("Compatible: Button");
  });

  it("step 4: a removed declaration is a major; a major needs Visible: and Upgrade steps:", T, async ({ expect }) => {
    const repo = await released();
    write(repo.lib, "api-surface.d.txt", SURFACE.replace('export type ButtonTone = "a" | "b";\n', ""));
    addSection(repo, "## 2.0.0 — 2026-10-01\nBreaking: ButtonTone is gone.\n");
    commit(repo.lib, "drop ButtonTone");
    let r = await release(repo, ["1.1.0"]);
    expect(r.stderr).toContain("ButtonTone is removed or changed");
    r = await release(repo, ["2.0.0"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toContain('a major needs "Visible:"');
    write(repo.lib, "CHANGELOG.md", read(repo.lib, "CHANGELOG.md").replace("Breaking: ButtonTone is gone.\n", `Breaking: ButtonTone is gone.\n${MAJOR_LINES}`));
    commit(repo.lib, "changelog");
    r = await release(repo, ["2.0.0"]);
    expect(r.status, r.stderr).toBe(0);
  });

  it("step 4: a modified or deleted existing baseline is a major, a pure rebaseline is exempt, a new baseline is a minor", T, async ({ expect }) => {
    let repo = await released();
    write(repo.lib, "gallery/__screenshots__/1440/workforce/button--matrix.png", "png-1-changed");
    addSection(repo, "## 1.1.0 — 2026-10-01\nFixed: the fill.\n");
    commit(repo.lib, "Button fill");
    let r = await release(repo, ["1.1.0"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toMatch(/"Button fill" modifies the existing baseline gallery\/__screenshots__\/1440\/workforce\/button--matrix\.png/);

    repo = await released();
    rmSync(path.join(repo.lib, "gallery/__screenshots__/375/workforce/button--matrix.png"));
    addSection(repo, "## 1.0.1 — 2026-10-01\nFixed: x.\n");
    commit(repo.lib, "drop a story");
    r = await release(repo, ["1.0.1"]);
    expect(r.stderr).toContain("deletes the existing baseline gallery/__screenshots__/375/workforce/button--matrix.png");

    // A pure rebaseline: only baselines and the pinned environment, titled as such.
    repo = await released();
    write(repo.lib, "gallery/__screenshots__/1440/workforce/button--matrix.png", "png-1-chromium-1200");
    write(repo.lib, "gallery/playwright.config.ts", "// pinned 1200\n");
    commit(repo.lib, "shots: rebaseline (Chromium 1200)");
    write(repo.lib, "README.md", "docs\n");
    addSection(repo, "## 1.0.1 — 2026-10-01\nFixed: the README.\n");
    commit(repo.lib, "docs");
    r = await release(repo, ["1.0.1"]);
    expect(r.status, r.stderr).toBe(0);

    // The same title with library source in the commit is not exempt.
    repo = await released();
    write(repo.lib, "gallery/__screenshots__/1440/workforce/button--matrix.png", "png-1-changed");
    write(repo.lib, "src/components/button.tsx", BUTTON.replace("rounded", "rounded-md"));
    addSection(repo, "## 1.0.1 — 2026-10-01\nFixed: x.\n");
    commit(repo.lib, "shots: rebaseline (and a radius)");
    r = await release(repo, ["1.0.1"]);
    expect(r.stderr).toContain("require a major");

    // A new baseline (a new story) is a minor.
    repo = await released();
    write(repo.lib, "gallery/__screenshots__/1440/workforce/tag--default.png", "png-3");
    addSection(repo, "## 1.0.1 — 2026-10-01\nAdded: a Tag story.\n");
    commit(repo.lib, "Tag story");
    r = await release(repo, ["1.0.1"]);
    expect(r.stderr).toContain("require a minor");
    expect(r.stderr).toContain("1 new baseline file(s)");
  });

  it("step 4: a new required brand variable and a Breaking: line are majors", T, async ({ expect }) => {
    let repo = await released();
    write(repo.lib, "styles/tokens.css", read(repo.lib, "styles/tokens.css").replace("--color-accent: var(--brand-accent);", "--color-accent: var(--brand-accent);\n  --color-rail: var(--brand-rail);"));
    addSection(repo, "## 1.1.0 — 2026-10-01\nAdded: --color-rail.\n");
    commit(repo.lib, "rail");
    let r = await release(repo, ["1.1.0"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toContain("styles/tokens.css: a new required brand variable --brand-rail");

    repo = await released();
    write(repo.lib, "README.md", "docs\n");
    addSection(repo, "## 1.0.1 — 2026-10-01\nBreaking: the README moved.\n");
    commit(repo.lib, "docs");
    r = await release(repo, ["1.0.1"]);
    expect(r.stderr).toContain("CHANGELOG.md: Breaking: the README moved.");
    expect(r.stderr).toContain("require a major");
  });

  it("step 4: an interaction-only style needs a Reviewed: line naming its component", T, async ({ expect }) => {
    const repo = await released();
    write(repo.lib, "src/components/button.tsx", BUTTON.replace("bg-primary text-white", "bg-primary text-white hover:bg-primary-hover"));
    addSection(repo, "## 1.0.1 — 2026-10-01\nFixed: the hover fill.\n");
    commit(repo.lib, "hover");
    let r = await release(repo, ["1.0.1"]);
    expect(r.status).toBe(1);
    expect(r.stderr).toContain('src/components/button.tsx changes an interaction-only style the baselines do not see; add "Reviewed: Button');
    write(repo.lib, "CHANGELOG.md", read(repo.lib, "CHANGELOG.md").replace("Fixed: the hover fill.\n", "Fixed: the hover fill.\nReviewed: Button - the hover fill is the documented primary-hover; the state shots cover it.\n"));
    commit(repo.lib, "changelog");
    r = await release(repo, ["1.0.1"]);
    expect(r.status, r.stderr).toBe(0);
    expect(r.stdout).toContain("reviewed by hand (src/components/button.tsx)");
  });
});
