// Declarations of sync-ops-ui.mjs - GENERATED by tools/api-surface.mjs from its JSDoc (tsc). Do not edit.
/**
 * @typedef {{ type: "comment" | "string" | "text" | "{" | "}" | ";", text: string, line: number }} CssToken
 */
/**
 * Splits CSS into tokens.
 * @param {string} css
 * @returns {CssToken[]}
 */
export function cssTokens(css: string): CssToken[];
/**
 * The theme gotcha (spec §8.5 check 6): inside an `@theme` block, a comment containing a
 * double-quote character. Tailwind's CSS parser has read such a quote as the start of a string
 * and silently dropped the declaration after the comment (the --color-tool incident of
 * 2026-08-28). Returns one problem per offending comment; empty means clean.
 * @param {string} css
 * @param {string} [file]
 * @returns {string[]}
 */
export function themeGotchas(css: string, file?: string): string[];
/**
 * @typedef {{ prelude: string, line: number, declarations: { name: string, value: string, line: number }[], nested: string[] }} CssRule
 */
/**
 * The top-level rules of a stylesheet, with their declarations. A top-level statement without
 * a block (an `@import`) comes back as a rule with an empty prelude-only entry in `statements`.
 * @param {string} css
 * @returns {{ rules: CssRule[], statements: { text: string, line: number }[] }}
 */
export function topLevelRules(css: string): {
    rules: CssRule[];
    statements: {
        text: string;
        line: number;
    }[];
};
/**
 * Parses the library's tokens.css into its contract. Throws on a malformed file (a declaration
 * outside a section, a value that does not fit its class): that is a library bug, never an app's.
 * @param {string} tokensCss
 * @returns {TokenContract}
 */
export function parseTokenContract(tokensCss: string): TokenContract;
/**
 * @typedef {{ l: number, c: number, h: number }} Oklch
 * @typedef {{ rgb: [number, number, number], oklch: Oklch | null, alpha: number }} Colour
 */
/**
 * Reads `oklch(L C H [/ A])`, `#rgb`, `#rrggbb` (with optional alpha), `white` or `black`.
 * Returns null for anything else.
 * @param {string} value
 * @returns {Colour | null}
 */
export function parseColour(value: string): Colour | null;
/**
 * OKLCH to linear-light sRGB (Björn Ottosson's OKLab matrices), unclamped.
 * @param {number} l @param {number} c @param {number} h
 * @returns {[number, number, number]}
 */
export function oklchToLinearSrgb(l: number, c: number, h: number): [number, number, number];
/**
 * WCAG relative luminance of a colour, its channels clipped to the sRGB gamut.
 * @param {Colour} colour
 */
export function luminance(colour: Colour): number;
/**
 * WCAG contrast ratio of two colours (1 to 21).
 * @param {Colour} a @param {Colour} b
 */
export function contrastRatio(a: Colour, b: Colour): number;
/**
 * The value a token takes under a brand (its declared `--brand-*` variables), or null when the
 * brand leaves a required one out. `white` is the literal the kit paints on primary and danger.
 * @param {TokenContract} contract
 * @param {Map<string, string>} brand
 * @param {string} token
 * @returns {string | null}
 */
export function resolveToken(contract: TokenContract, brand: Map<string, string>, token: string): string | null;
/**
 * The declarations of a brand file as a Map, with every problem of check 1 (only `selector`
 * rules, only `--brand-*` / `--ops-*` custom properties, no at-rule, no nesting).
 * @param {string} css
 * @param {{ selector?: string, file?: string }} [options]
 */
export function readBrandCss(css: string, { selector, file }?: {
    selector?: string;
    file?: string;
}): {
    values: Map<string, string>;
    problems: string[];
};
/**
 * Every problem of an app's brand.css against the token contract (spec §8.5 checks 1-4).
 * Empty means the brand holds.
 * @param {string} css the brand file
 * @param {TokenContract} contract from parseTokenContract(tokens.css)
 * @param {{ selector?: string, file?: string }} [options] `selector` is `:root` for an app;
 *   the gallery fixtures use `html[data-brand=<name>]`.
 * @returns {string[]}
 */
export function checkBrandCss(css: string, contract: TokenContract, options?: {
    selector?: string;
    file?: string;
}): string[];
/**
 * @typedef {{ from: string, to: string }} ShipRule
 * @typedef {{ files: ShipRule[] }} ShipManifest
 * @typedef {{ src: string, dest: string }} ShipEntry
 */
/**
 * The files a release ships and where each lands, sorted by destination. Throws on a malformed
 * manifest (a rule of an unknown shape, two sources for one destination).
 * @param {ShipManifest} ship
 * @param {string[]} files every path in the release commit (git ls-tree -r --name-only)
 * @param {string} vendorDir
 * @returns {ShipEntry[]}
 */
export function shipPlan(ship: ShipManifest, files: string[], vendorDir: string): ShipEntry[];
/**
 * The destination allow-list (spec §5.2 step 4): under the vendor folder, or exactly this
 * script or its declarations. A release can never write app code.
 * @param {string} dest
 * @param {string} vendorDir
 */
export function isAllowedDestination(dest: string, vendorDir: string): boolean;
/**
 * The first-line header of a shipped file (spec §5.2 step 5). No double quote anywhere, so a
 * CSS header can never trip the theme gotcha.
 * @param {string} dest
 * @param {string} version
 * @param {string} sha7
 */
export function generatedHeader(dest: string, version: string, sha7: string): string;
/** @param {string | Buffer} content */
export function sha256(content: string | Buffer): string;
/** @param {string} v @returns {[number, number, number] | null} */
export function parseVersion(v: string): [number, number, number] | null;
/** @param {string} a @param {string} b */
export function compareVersions(a: string, b: string): 0 | 1 | -1;
/**
 * Does `version` satisfy `range`? Enough of npm's ranges for peerDependencies.
 * @param {string} version
 * @param {string} range
 */
export function satisfies(version: string, range: string): boolean;
/** @param {string} name */
export function isOsLitter(name: string): boolean;
/** JSON with sorted keys and a trailing newline: a re-run writes the same bytes. */
export function stableJson(value: unknown): string;
/**
 * @typedef {{ source?: string, vendorDir: string, globalsCss: string, brandCss: string, extensions: string[], local: string[], bindings: string[], wrappersDir: string }} AppConfig
 * @typedef {{ commit: string, files: Record<string, string>, version: string, dev?: boolean }} Lock
 */
/**
 * The app's ops-ui.config.json (spec §3.3), with defaults for what a config may leave out.
 * @param {string} appRoot
 * @returns {AppConfig}
 */
export function readConfig(appRoot: string): AppConfig;
/**
 * The brand contract and the theme gotcha against the app's own files (spec §8.5 checks 1-4
 * and 6). A missing brand.css counts only once globals.css imports the vendored tokens: in the
 * vendor-only step (F2/W3) nothing reads the brand yet.
 * @param {string} appRoot
 * @param {AppConfig} config
 * @param {string} tokensCss the library's tokens.css (at the release, or vendored)
 * @returns {{ brand: string[], theme: string[], notes: string[] }}
 */
export function checkAppStyles(appRoot: string, config: AppConfig, tokensCss: string): {
    brand: string[];
    theme: string[];
    notes: string[];
};
/**
 * @param {string} appRoot
 * @returns {Promise<{ ok: boolean, version: string, dev: boolean, edited: string[], missing: string[], unknown: string[], brand: string[], theme: string[] }>}
 */
export function checkVendor(appRoot: string): Promise<{
    ok: boolean;
    version: string;
    dev: boolean;
    edited: string[];
    missing: string[];
    unknown: string[];
    brand: string[];
    theme: string[];
}>;
/**
 * Where the library repo is: --repo, $OPS_UI_REPO, config.source, ../ops-ui.
 * @param {string} appRoot
 * @param {AppConfig} config
 * @param {string | undefined} flag
 */
export function findRepo(appRoot: string, config: AppConfig, flag: string | undefined): string;
/**
 * The release commit of `version`: exactly one `release: vX.Y.Z` on main, agreeing with the
 * release/vX.Y.Z branch when that exists, whose package.json and src/version.ts say X.Y.Z.
 * @param {string} repo
 * @param {string} version
 * @returns {string}
 */
export function resolveRelease(repo: string, version: string): string;
/**
 * Everything a sync needs from the release commit.
 * @param {string} repo
 * @param {string} commit
 * @param {string} version
 * @param {string} vendorDir
 */
export function readRelease(repo: string, commit: string, version: string, vendorDir: string): {
    plan: ShipEntry[];
    contents: Map<string, string>;
    pkg: {
        version?: string;
        peerDependencies?: Record<string, string>;
    };
    tokensCss: string;
    changelog: string;
};
/**
 * The CHANGELOG sections after `from` up to and including `to` (spec §4.3 headings
 * `## X.Y.Z — date`), newest first as the file holds them.
 * @param {string} changelog
 * @param {string | null} from
 * @param {string} to
 */
export function changelogBetween(changelog: string, from: string | null, to: string): string[];
/**
 * @typedef {{ version?: string, ref?: string, repo?: string, dryRun?: boolean, discardLocalEdits?: boolean, allowDowngrade?: boolean }} SyncOptions
 */
/**
 * @param {string} appRoot
 * @param {SyncOptions} options
 * @param {(line: string) => void} log
 * @returns {number} the exit code
 */
export function sync(appRoot: string, options: SyncOptions, log: (line: string) => void): number;
/**
 * The source with every comment and the contents of every string, template and regular
 * expression literal blanked to spaces; newlines stay, so every line keeps its number and a
 * statement that starts a line still starts it. A small lexer, not a regex: a quoted `image/*`
 * must not open a comment, and a `//` inside a string must not end its line. Template literals
 * nest (`${ … }` is code again). A `/` is a regular expression after an operator, an opening
 * bracket, a keyword or the start of the file, and a division after a value; a would-be regular
 * expression that reaches the end of its line is read as a division instead, so a misreading
 * cannot swallow the next line. JSX text is read as code (the library test compares every
 * component's exports with the TypeScript AST, so a component that confused this lexer would
 * fail before any release).
 * @param {string} source
 * @returns {string}
 */
export function blankNonCode(source: string): string;
/**
 * The runtime and type exports of a module, in source order, from its top-level export
 * statements (read after blankNonCode, so no comment or literal can hide or fake one).
 * @param {string} source
 * @returns {{ runtime: string[], types: string[] }}
 */
export function moduleExports(source: string): {
    runtime: string[];
    types: string[];
};
/**
 * The kit's internal runtime imports: for every component module in `sources` (name -> source),
 * the sibling components it imports at run time (`import type` and all-type specifier lists
 * left out: they vanish at compile time). Kit files import each other RELATIVELY, so a wrapper
 * cannot re-route them: ConfirmDialog always renders the vendored Dialog.
 * @param {Map<string, string>} sources
 * @returns {Map<string, string[]>}
 */
export function kitImportGraph(sources: Map<string, string>): Map<string, string[]>;
/**
 * Every component that renders `name` at run time, directly or through another component: what a
 * KIT-OVERRIDE of `name` must override too (spec §6.4), or those modules keep the vendored one.
 * @param {Map<string, string[]>} graph from kitImportGraph
 * @param {string} name
 * @returns {string[]}
 */
export function kitDependents(graph: Map<string, string[]>, name: string): string[];
/**
 * kitImportGraph of the vendored components of an app (for its vendor test's KIT-OVERRIDE check).
 * @param {string} appRoot
 */
export function vendoredKitGraph(appRoot: string): Map<string, string[]>;
/**
 * Creates a pure wrapper for every vendored component without one; never overwrites.
 * @param {string} appRoot
 * @param {(line: string) => void} log
 * @returns {number}
 */
export function writeWrappers(appRoot: string, log: (line: string) => void): number;
/**
 * @param {string[]} argv
 * @returns {{ command: "sync" | "check" | "write-wrappers" } & SyncOptions}
 */
export function parseArgs(argv: string[]): {
    command: "sync" | "check" | "write-wrappers";
} & SyncOptions;
/**
 * @param {string[]} argv
 * @param {string} appRoot
 * @returns {Promise<number>}
 */
export function main(argv: string[], appRoot?: string): Promise<number>;
export namespace TINT_BOUNDS {
    let lightness: number;
    let chroma: number;
}
/** Tunable status (spec §8.3): the hue range per brand variable. */
export const TUNABLE_HUES: {
    "--brand-success": number[];
    "--brand-success-subtle": number[];
};
/**
 * The contrast every brand must meet (spec §8.5 check 4). `white` is the kit's literal
 * text-white; `onlyWhenSet` skips the pair while the app leaves that brand variable unset.
 * @type {{ fg: string, bg: string, min: number, onlyWhenSet?: string }[]}
 */
export const CONTRAST_PAIRS: {
    fg: string;
    bg: string;
    min: number;
    onlyWhenSet?: string;
}[];
/**
 * The fixed status pairs (spec §8.5 check 5): library colours, checked once by the library test.
 * @type {{ fg: string, bg: string, min: number }[]}
 */
export const FIXED_PAIRS: {
    fg: string;
    bg: string;
    min: number;
}[];
/** The destinations outside the vendor folder: this script and its declarations. */
export const SYNC_DEST: "scripts/sync-ops-ui.mjs";
export const SYNC_TYPES_DEST: "scripts/sync-ops-ui.d.mts";
export const LOCK_FILE: "ops-ui.lock.json";
export const CONFIG_FILE: "ops-ui.config.json";
export type CssToken = {
    type: "comment" | "string" | "text" | "{" | "}" | ";";
    text: string;
    line: number;
};
export type CssRule = {
    prelude: string;
    line: number;
    declarations: {
        name: string;
        value: string;
        line: number;
    }[];
    nested: string[];
};
export type Oklch = {
    l: number;
    c: number;
    h: number;
};
export type Colour = {
    rgb: [number, number, number];
    oklch: Oklch | null;
    alpha: number;
};
export type ShipRule = {
    from: string;
    to: string;
};
export type ShipManifest = {
    files: ShipRule[];
};
export type ShipEntry = {
    src: string;
    dest: string;
};
export type AppConfig = {
    source?: string;
    vendorDir: string;
    globalsCss: string;
    brandCss: string;
    extensions: string[];
    local: string[];
    bindings: string[];
    wrappersDir: string;
};
export type Lock = {
    commit: string;
    files: Record<string, string>;
    version: string;
    dev?: boolean;
};
export type SyncOptions = {
    version?: string;
    ref?: string;
    repo?: string;
    dryRun?: boolean;
    discardLocalEdits?: boolean;
    allowDowngrade?: boolean;
};
export type TokenClass = "fixed" | "required" | "role" | "tint" | "tunable";
export type ContractToken = {
    token: string;
    cls: TokenClass;
    value: string;
    brand?: string;
    fallbackBrand?: string;
    fallback?: string;
};
export type TokenContract = {
    tokens: ContractToken[];
};
