// tools/api-surface.mjs - regenerates api-surface.d.txt (spec §4.1): the declaration surface of
// src/, i.e. the .d.ts output of `tsc --emitDeclarationOnly` over every module under src/,
// concatenated file by file in path order, each file under a `// <path>.d.ts` line, with
// comments removed (a doc comment is not API). The release script diffs it to classify a
// release (added lines = minor at least, a removed or changed line = major); `pnpm test` fails
// when it is stale.
//
//   node tools/api-surface.mjs          write api-surface.d.txt
//   node tools/api-surface.mjs --check  exit 1 when api-surface.d.txt is not current

import { execFileSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const SURFACE_FILE = path.join(root, "api-surface.d.txt");

/** The declaration surface of src/ as text. */
export function apiSurface() {
  const tmp = mkdtempSync(path.join(os.tmpdir(), "ops-ui-api-"));
  try {
    const out = path.join(tmp, "out");
    const base = JSON.parse(readFileSync(path.join(root, "tsconfig.json"), "utf8")).compilerOptions;
    const tsconfig = {
      compilerOptions: {
        ...base,
        plugins: undefined,
        noEmit: false,
        incremental: false,
        allowJs: false,
        declaration: true,
        emitDeclarationOnly: true,
        // Doc comments are not API: editing one must never classify a release as a major.
        removeComments: true,
        outDir: out,
        rootDir: path.join(root, "src"),
      },
      include: [path.join(root, "src/**/*.ts"), path.join(root, "src/**/*.tsx")],
    };
    const config = path.join(tmp, "tsconfig.json");
    writeFileSync(config, JSON.stringify(tsconfig));
    execFileSync(process.execPath, [path.join(root, "node_modules/typescript/bin/tsc"), "-p", config], {
      cwd: root,
      stdio: ["ignore", "pipe", "pipe"],
    });
    const files = [];
    const walk = (dir) => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else if (entry.name.endsWith(".d.ts")) files.push(path.relative(out, full).split(path.sep).join("/"));
      }
    };
    walk(out);
    files.sort();
    const header =
      "// @latro/ops-ui declaration surface - GENERATED by tools/api-surface.mjs (tsc --emitDeclarationOnly over src/).\n" +
      "// Do not edit. `pnpm test` fails when this file is stale; the release script classifies releases by its diff.\n";
    return (
      header +
      files
        .map((file) => {
          const body = readFileSync(path.join(out, file), "utf8")
            .split("\n")
            .map((line) => line.trimEnd())
            .join("\n")
            .trim();
          return `\n// src/${file}\n${body}\n`;
        })
        .join("")
    );
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const text = apiSurface();
  if (process.argv.includes("--check")) {
    const current = existsSync(SURFACE_FILE) ? readFileSync(SURFACE_FILE, "utf8") : "";
    if (current !== text) {
      console.error("api-surface.d.txt is stale: run node tools/api-surface.mjs");
      process.exit(1);
    }
    console.log("api-surface.d.txt is current");
  } else {
    writeFileSync(SURFACE_FILE, text);
    console.log(`wrote ${path.relative(process.cwd(), SURFACE_FILE)}`);
  }
}
