// tools/api-surface.mjs - regenerates the two generated declaration files; `pnpm test` fails
// when either is stale.
//
// 1. api-surface.d.txt (spec §4.1): the declaration surface of src/, i.e. the .d.ts output of
//    `tsc --emitDeclarationOnly` over every module under src/, concatenated file by file in path
//    order, each file under a `// <path>.d.ts` line, with comments removed (a doc comment is not
//    API). The release script diffs it to classify a release (added lines = minor at least, a
//    removed or changed line = major).
// 2. sync/sync-ops-ui.d.mts: the declarations of the sync script, from its JSDoc, shipped beside
//    it as scripts/sync-ops-ui.d.mts. An app whose tsconfig has allowJs off (PrefabOps) can then
//    type-check the vendor test that imports checkVendor from the .mjs; with allowJs on, the
//    declaration file wins over the script, so it must stay complete.
//
//   node tools/api-surface.mjs          write both
//   node tools/api-surface.mjs --check  exit 1 when either is not current

import { execFileSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const SURFACE_FILE = path.join(root, "api-surface.d.txt");
export const SYNC_DECLARATIONS_FILE = path.join(root, "sync/sync-ops-ui.d.mts");

/** The declarations of sync/sync-ops-ui.mjs, generated from its JSDoc. */
export function syncDeclarations() {
  const tmp = mkdtempSync(path.join(os.tmpdir(), "ops-ui-sync-dts-"));
  try {
    execFileSync(
      process.execPath,
      [
        path.join(root, "node_modules/typescript/bin/tsc"),
        "--allowJs",
        "--declaration",
        "--emitDeclarationOnly",
        "--skipLibCheck",
        "--strict",
        "--target",
        "es2022",
        "--module",
        "nodenext",
        "--moduleResolution",
        "nodenext",
        "--types",
        "node",
        "--outDir",
        tmp,
        path.join(root, "sync/sync-ops-ui.mjs"),
      ],
      { cwd: root, stdio: ["ignore", "pipe", "pipe"] },
    );
    const body = readFileSync(path.join(tmp, "sync-ops-ui.d.mts"), "utf8")
      .split("\n")
      .map((line) => line.trimEnd())
      .join("\n")
      .trim();
    return (
      "// Declarations of sync-ops-ui.mjs - GENERATED by tools/api-surface.mjs from its JSDoc (tsc). Do not edit.\n" +
      `${body}\n`
    );
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

/** The declaration surface of src/ as text. */
export function apiSurface() {
  const tmp = mkdtempSync(path.join(os.tmpdir(), "ops-ui-api-"));
  try {
    const out = path.join(tmp, "out");
    const base = JSON.parse(readFileSync(path.join(root, "tsconfig.json"), "utf8")).compilerOptions;
    const tsconfig = {
      compilerOptions: {
        ...base,
        plugins: undefined,
        noEmit: false,
        incremental: false,
        allowJs: false,
        declaration: true,
        emitDeclarationOnly: true,
        // Doc comments are not API: editing one must never classify a release as a major.
        removeComments: true,
        outDir: out,
        rootDir: path.join(root, "src"),
      },
      include: [path.join(root, "src/**/*.ts"), path.join(root, "src/**/*.tsx")],
    };
    const config = path.join(tmp, "tsconfig.json");
    writeFileSync(config, JSON.stringify(tsconfig));
    execFileSync(process.execPath, [path.join(root, "node_modules/typescript/bin/tsc"), "-p", config], {
      cwd: root,
      stdio: ["ignore", "pipe", "pipe"],
    });
    const files = [];
    const walk = (dir) => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else if (entry.name.endsWith(".d.ts")) files.push(path.relative(out, full).split(path.sep).join("/"));
      }
    };
    walk(out);
    files.sort();
    const header =
      "// @latro/ops-ui declaration surface - GENERATED by tools/api-surface.mjs (tsc --emitDeclarationOnly over src/).\n" +
      "// Do not edit. `pnpm test` fails when this file is stale; the release script classifies releases by its diff.\n";
    return (
      header +
      files
        .map((file) => {
          const body = readFileSync(path.join(out, file), "utf8")
            .split("\n")
            .map((line) => line.trimEnd())
            .join("\n")
            .trim();
          return `\n// src/${file}\n${body}\n`;
        })
        .join("")
    );
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const outputs = [
    [SURFACE_FILE, apiSurface()],
    [SYNC_DECLARATIONS_FILE, syncDeclarations()],
  ];
  if (process.argv.includes("--check")) {
    let stale = false;
    for (const [file, text] of outputs) {
      const current = existsSync(file) ? readFileSync(file, "utf8") : "";
      const name = path.relative(root, file);
      if (current !== text) {
        console.error(`${name} is stale: run node tools/api-surface.mjs`);
        stale = true;
      } else {
        console.log(`${name} is current`);
      }
    }
    if (stale) process.exit(1);
  } else {
    for (const [file, text] of outputs) {
      writeFileSync(file, text);
      console.log(`wrote ${path.relative(process.cwd(), file)}`);
    }
  }
}
