// tools/pull-brands.mjs - copies each app's src/app/brand.css into the gallery's brand fixture
// (spec §11.2): `:root {` becomes `html[data-brand=<brand>] {`, nothing else changes, so the
// gallery shoots every story in exactly the colours the app ships. Read through git only (the
// apps' working trees belong to other sessions); an app without a brand.css yet (before steps
// F3 / W4 / P2) keeps its hand-written fixture.
//
//   node tools/pull-brands.mjs [--ref HEAD] [--workforce ../workforce-ops] [--finaops ../fina-ops] [--prefab ../prefab-ops-platform]
//
// Afterwards run pnpm test (the contract checks every fixture) and pnpm shots: a changed brand
// is a changed baseline.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { checkBrandCss, parseTokenContract } from "../sync/sync-ops-ui.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/** Where each brand's app keeps its brand.css. */
export const BRAND_SOURCES = {
  workforce: { repo: "../workforce-ops", file: "src/app/brand.css" },
  finaops: { repo: "../fina-ops", file: "src/app/brand.css" },
  prefab: { repo: "../prefab-ops-platform", file: "apps/web/src/app/brand.css" },
};

/**
 * The gallery fixture for an app's brand.css.
 * @param {string} css the app's brand.css
 * @param {string} brand
 * @param {string} source e.g. "workforce-ops@abc1234"
 */
export function fixtureFromBrandCss(css, brand, source) {
  const roots = css.match(/^:root\s*\{/gm) ?? [];
  if (roots.length !== 1) throw new Error(`${brand}: expected exactly one :root rule in brand.css, found ${roots.length}`);
  const body = css.replace(/^:root\s*\{/m, `html[data-brand=${brand}] {`);
  return `/* ${brand} brand fixture - GENERATED by tools/pull-brands.mjs from ${source}. Do not edit; change the app's brand.css and pull again. */\n${body}`;
}

function main(argv) {
  const opts = { ref: "HEAD" };
  for (let i = 0; i < argv.length; i++) {
    const flag = argv[i].replace(/^--/, "");
    if (!["ref", ...Object.keys(BRAND_SOURCES)].includes(flag) || argv[i + 1] === undefined) {
      console.error(`usage: node tools/pull-brands.mjs [--ref HEAD] [--workforce <repo>] [--finaops <repo>] [--prefab <repo>]`);
      return 2;
    }
    opts[flag] = argv[++i];
  }
  const contract = parseTokenContract(readFileSync(path.join(root, "styles/tokens.css"), "utf8"));
  let failed = false;
  for (const [brand, source] of Object.entries(BRAND_SOURCES)) {
    const repo = path.resolve(root, opts[brand] ?? source.repo);
    let css;
    let sha;
    try {
      sha = execFileSync("git", ["-C", repo, "rev-parse", "--short=7", opts.ref], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
      css = execFileSync("git", ["-C", repo, "show", `${opts.ref}:${source.file}`], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
    } catch {
      console.log(`${brand}: no ${source.file} at ${opts.ref} in ${repo} yet - fixture kept`);
      continue;
    }
    const problems = checkBrandCss(css, contract, { file: `${path.basename(repo)}/${source.file}` });
    if (problems.length > 0) {
      failed = true;
      for (const p of problems) console.error(`${brand}: ${p}`);
      continue;
    }
    const fixture = fixtureFromBrandCss(css, brand, `${path.basename(repo)}@${sha}`);
    writeFileSync(path.join(root, "gallery/brands", `${brand}.css`), fixture);
    console.log(`${brand}: gallery/brands/${brand}.css from ${path.basename(repo)}@${sha}`);
  }
  return failed ? 1 : 0;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  process.exit(main(process.argv.slice(2)));
}
